language: android
dist: xenial
android:
  components:
    - tools
    - platform-tools

    # The BuildTools version
    - build-tools-31.0.0

    # The SDK version
    - android-30

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # System image run emulator(s) during tests
    - sys-img-x86-android-30
before_install:
  - yes | sdkmanager "platforms;android-30"
  - chmod +x gradlew
  - chmod +x $TRAVIS_BUILD_DIR/install-jdk.sh
  - export JAVA_HOME=$HOME/openjdk11
  - $TRAVIS_BUILD_DIR/install-jdk.sh -F 11 --target $JAVA_HOME
notifications:
  email:
    recipients:
      - baross.anna@gmail.com
    on_success: never
    on_failure: always
script:
  - ./gradlew build
