openapi: 3.0.0
info:
  title: bored-api
  version: '1.0'
  description: Bored API documentation
  contact:
    name: Anna Baross
    email: baross.anna@gmail.com
servers:
  - url: 'http://www.boredapi.com/api'
paths:
  /activity:
    get:
      summary: Your GET endpoint
      tags:
        - occupation
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Occupation'
      operationId: get-activity
      parameters:
        - schema:
            type: string
          in: query
          name: key
          description: ' A unique numeric id'
        - schema:
            type: string
          in: query
          name: type
          description: Find a random activity with a given type
        - schema:
            type: integer
          in: query
          name: participants
          description: Find a random activity with a given number of participants
        - schema:
            type: number
          in: query
          name: price
          description: Find an activity with a specified price
        - schema:
            type: string
          in: query
          name: maxprice
          description: Find an event with a specified max price
      description: Get random occupation object
components:
  schemas:
    Occupation:
      description: Represents an occupation
      type: object
      properties:
        activity:
          type: string
          minLength: 1
          description: Description of the queried activity
        accessibility:
          type: number
          description: |-
            A factor describing how possible an event is to do with zero being the most accessible

            [0.0, 1.0]
        type:
          type: string
          minLength: 1
          enum:
            - education
            - recreational
            - social
            - diy
            - charity
            - cooking
            - relaxation
            - music
            - busywork
          description: Type of the activity
        participants:
          type: number
          description: The number of people that this activity could involve
        price:
          type: number
          description: |-
            A factor describing the cost of the event with zero being free

            [0, 1]
        link:
          type: string
          minLength: 1
          description: Provided URL for the activity's starter
        key:
          type: string
          minLength: 1
          description: A unique numeric id
      required:
        - activity
        - accessibility
        - type
        - participants
        - price
        - link
        - key
tags:
  - name: occupation
